# Generated by Django 5.2.10 on 2026-02-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_remove_article_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('subjectivity_ratio', models.FloatField(blank=True, help_text='Proportion of subjective sentences (0.0=fully objective, 1.0=fully subjective)', null=True)),
                ('sentence_count', models.IntegerField(blank=True, help_text='Total sentences analyzed', null=True)),
                ('subjective_sentence_count', models.IntegerField(blank=True, help_text='Number of sentences classified as subjective', null=True)),
                ('avg_subjectivity_confidence', models.FloatField(blank=True, help_text='Average classifier confidence across all sentences', null=True)),
                ('leaning_left', models.FloatField(blank=True, help_text='Probability of left-leaning framing (0.0-1.0)', null=True)),
                ('leaning_center', models.FloatField(blank=True, help_text='Probability of center framing (0.0-1.0)', null=True)),
                ('leaning_right', models.FloatField(blank=True, help_text='Probability of right-leaning framing (0.0-1.0)', null=True)),
                ('framing_chunks_analyzed', models.IntegerField(blank=True, help_text='Number of text chunks analyzed for framing', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('model_versions', models.JSONField(blank=True, default=dict, help_text='Model names used for this analysis run')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='articles.article')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='analysis_ar_status_5bb734_idx')],
            },
        ),
    ]
