# Generated by Django 4.2.27 on 2026-01-26 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('documents_processed', models.IntegerField(default=0)),
                ('documents_total', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_runs', to='experiments.promptversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='datasets.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedNugget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nugget_text', models.TextField()),
                ('nugget_type', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_nuggets', to='datasets.document')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuggets', to='extraction.extractionrun')),
            ],
        ),
    ]
