# Generated by Django 4.2.27 on 2025-12-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('article_count', models.IntegerField(default=0)),
                ('source_count', models.IntegerField(default=0)),
                ('trending_score', models.FloatField(default=0.0)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('first_article_at', models.DateTimeField(null=True)),
                ('last_article_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-trending_score', '-last_article_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('cluster_rank', models.IntegerField(default=0)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='articles.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='topics.topic')),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('topic', 'article')},
            },
        ),
    ]
