# Generated by Django 5.2.10 on 2026-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='event_registry_uri',
            field=models.CharField(blank=True, help_text='Event URI in Event Registry', max_length=200, null=True, unique=True),
        ),
    ]
