# Generated by Django 4.2.27 on 2026-02-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_topic_event_registry_uri"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["-trending_score", "-last_article_at"],
                name="topics_topi_trendin_b1c54d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["event_registry_uri"], name="topics_topi_event_r_b7d108_idx"
            ),
        ),
    ]
