# Generated by Django 4.2.27 on 2026-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_topic_topics_topi_trendin_b1c54d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
