# Generated by Django 5.2.10 on 2026-02-06 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_remove_article_embedding_and_more'),
        ('topics', '0002_topic_event_registry_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Nuggets'), ('deduplicating', 'Deduplicating'), ('scoring', 'Scoring Articles'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('articles_processed', models.IntegerField(default=0)),
                ('nugget_count', models.IntegerField(default=0)),
                ('vital_nugget_count', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('similarity_threshold', models.FloatField(default=0.85)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_pool', to='topics.topic')),
            ],
            options={
                'ordering': ['-built_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsensusNugget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nugget_text', models.TextField()),
                ('importance', models.CharField(choices=[('vital', 'Vital'), ('okay', 'Okay')], default='okay', max_length=10)),
                ('source_count', models.IntegerField(default=1)),
                ('source_names', models.JSONField(default=list)),
                ('cluster_id', models.IntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuggets', to='consensus.consensuspool')),
            ],
            options={
                'ordering': ['-source_count', 'cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='OmissionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('omission_rate', models.FloatField(blank=True, null=True)),
                ('vital_omission_rate', models.FloatField(blank=True, null=True)),
                ('coverage_score', models.FloatField(blank=True, null=True)),
                ('support_count', models.IntegerField(default=0)),
                ('partial_support_count', models.IntegerField(default=0)),
                ('not_support_count', models.IntegerField(default=0)),
                ('total_nuggets', models.IntegerField(default=0)),
                ('vital_support_count', models.IntegerField(default=0)),
                ('vital_total', models.IntegerField(default=0)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omission_scores', to='articles.article')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='consensus.consensuspool')),
            ],
            options={
                'ordering': ['-coverage_score'],
                'unique_together': {('pool', 'article')},
            },
        ),
        migrations.CreateModel(
            name='RawNugget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nugget_text', models.TextField()),
                ('nugget_type', models.CharField(blank=True, max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_nuggets', to='articles.article')),
                ('consensus_nugget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_nuggets', to='consensus.consensusnugget')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_nuggets', to='consensus.consensuspool')),
            ],
            options={
                'ordering': ['article', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NuggetJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('support', 'Support'), ('partial_support', 'Partial Support'), ('not_support', 'Not Support')], max_length=20)),
                ('consensus_nugget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='consensus.consensusnugget')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='consensus.omissionscore')),
            ],
            options={
                'unique_together': {('score', 'consensus_nugget')},
            },
        ),
    ]
