# Generated by Django 5.2.10 on 2026-02-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omissionscore',
            name='vital_partial_support_count',
            field=models.IntegerField(default=0),
        ),
    ]
