# Generated by Django 4.2.27 on 2026-02-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consensus", "0002_add_vital_partial_support_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consensusnugget",
            name="importance",
            field=models.CharField(
                choices=[("vital", "Vital"), ("okay", "Okay")],
                db_index=True,
                default="okay",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="omissionscore",
            index=models.Index(
                fields=["pool", "-coverage_score"],
                name="consensus_o_pool_id_b5be47_idx",
            ),
        ),
    ]
