# Generated by Django 4.2.27 on 2026-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consensus", "0003_add_missing_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consensusnugget",
            options={"ordering": ["tier", "-source_count", "cluster_id"]},
        ),
        migrations.AddField(
            model_name="consensusnugget",
            name="tier",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Headline"), (2, "Context"), (3, "Detail")],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consensuspool",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("extracting", "Extracting Nuggets"),
                    ("deduplicating", "Deduplicating"),
                    ("post_processing", "Post-Processing"),
                    ("scoring", "Scoring Articles"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
