# Generated by Django 4.2.27 on 2026-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consensus",
            "0004_alter_consensusnugget_options_consensusnugget_tier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="consensuspool",
            name="report_cache",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
