# Generated by Django 4.2.27 on 2026-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consensus", "0005_add_report_cache"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consensusnugget",
            options={
                "ordering": ["theme_order", "tier", "-source_count", "cluster_id"]
            },
        ),
        migrations.AddField(
            model_name="consensusnugget",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="consensusnugget",
            name="theme_order",
            field=models.IntegerField(default=0),
        ),
    ]
