# Generated by Django 4.2.27 on 2026-04-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consensus", "0006_add_nugget_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contradiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "explanation",
                    models.TextField(
                        help_text="LLM-generated explanation of the contradiction."
                    ),
                ),
                (
                    "nugget_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions_as_a",
                        to="consensus.consensusnugget",
                    ),
                ),
                (
                    "nugget_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions_as_b",
                        to="consensus.consensusnugget",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions",
                        to="consensus.consensuspool",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("nugget_a", "nugget_b")},
            },
        ),
    ]
