# Generated by Django 5.2.10 on 2026-02-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0002_topic_event_registry_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeutralSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('summary_text', models.TextField(blank=True)),
                ('nuggets_used', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neutral_summary', to='topics.topic')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
