# Generated by Django 4.2.27 on 2025-12-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('website_url', models.URLField()),
                ('logo_url', models.URLField(blank=True)),
                ('discovery_method', models.CharField(choices=[('rss', 'RSS Feed'), ('sitemap', 'Sitemap XML'), ('homepage', 'Homepage Scraping')], default='rss', max_length=20)),
                ('discovery_url', models.URLField(help_text='RSS feed URL, sitemap URL, or homepage URL for scraping')),
                ('article_link_selector', models.CharField(blank=True, help_text='CSS selector for article links (homepage scraping only)', max_length=200)),
                ('known_bias', models.CharField(choices=[('far_left', 'Far Left'), ('left', 'Left'), ('center_left', 'Center Left'), ('center', 'Center'), ('center_right', 'Center Right'), ('right', 'Right'), ('far_right', 'Far Right')], default='center', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('scrape_frequency_hours', models.IntegerField(default=1)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary/description')),
                ('content', models.TextField(blank=True, help_text='Full article text')),
                ('word_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraped', 'Content Scraped'), ('embedded', 'Embeddings Generated'), ('clustered', 'Topic Assigned'), ('complete', 'Processing Complete'), ('failed', 'Processing Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.source')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='articles_ar_status_cbb22b_idx'), models.Index(fields=['source', 'published_at'], name='articles_ar_source__f67b7d_idx')],
            },
        ),
    ]
