# Generated by Django 4.2.27 on 2025-12-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, max_length=2000, unique=True),
        ),
    ]
