# Generated by Django 5.2.10 on 2026-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_increase_slug_url_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='article',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='source',
            name='article_link_selector',
        ),
        migrations.RemoveField(
            model_name='source',
            name='discovery_method',
        ),
        migrations.RemoveField(
            model_name='source',
            name='discovery_url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_scraped_at',
        ),
        migrations.RemoveField(
            model_name='source',
            name='scrape_frequency_hours',
        ),
        migrations.AddField(
            model_name='article',
            name='event_registry_uri',
            field=models.CharField(blank=True, help_text='Article URI in Event Registry', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='Sentiment score from Event Registry (-1 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='event_registry_uri',
            field=models.CharField(blank=True, default='', help_text="Source URI in Event Registry (e.g. 'npr.org')", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Processing Complete'), ('failed', 'Processing Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
