# Generated by Django 4.2.27 on 2026-02-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_article_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
