# Generated by Django 4.2.27 on 2026-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_add_missing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_wire_content",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this article is a republished wire service story (AP, Reuters, AFP, etc.)",
            ),
        ),
    ]
