# Generated by Django 4.2.27 on 2026-04-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_is_wire_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="known_bias",
        ),
    ]
