# Generated by Django 4.2.27 on 2026-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_remove_known_bias"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
