# Generated by Django 4.2.27 on 2026-05-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_add_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="wire_original",
            field=models.ForeignKey(
                blank=True,
                help_text="If this article is a wire copy, points to the cluster anchor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wire_copies",
                to="articles.article",
            ),
        ),
    ]
